### ISSUE TITLE
ActiveSupport::NumberHelper not available in decorators

### ISSUE THREAD

**Issue by paulelliott** [vicramon/little_decorator#4]
The view_context that LittleDecorator delegates helpers to does not include ActiveSupport::NumberHelper, although the methods there are available as helpers in regular Rails views. It would be nice if they were included in the standard available helper methods.

**Comment by vicramon** [comment]
I'm having trouble recreating the issue, could you please provide more details?

**Comment by vicramon** [comment]
This seems to work just fine. Closing until someone can provide an example.

**Comment by tmock12** [comment]
works for me. I tried number_to_currency and it worked magnificently.
