### ISSUE TITLE
Decorators do not play nice with polymorphic urls

### ISSUE THREAD

**Issue by paulelliott** [vicramon/little_decorator#5]
If I use a decorated object in a polymorphic URL, it does not resolve properly.

In other words, `link_to 'Blog Post', blog_post` will not produce an anchor tag pointing to `/blog_posts/4`.

**Comment by webdestroya** [comment]
+1

It generates routes like:

`http://site.com/things/%23%3CThingDecorator:0x007fd36566afe0%3E/edit`

Edit: I can sort of get what I want by doing:

``` ruby
def to_param
  record.id.to_s
end
```
